books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2024-06-01",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2023-01-01",
        "page_count": 552,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2025-05-01",
        "page_count": 672,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-05-01",
        "page_count": 1012,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Addison-Wesley Professional",
        "published_date": "2024-11-01",
        "page_count": 672,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Python Cookbook",
        "author": "David Beazley",
        "publisher": "O'Reilly Media",
        "published_date": "2013-05-01",
        "page_count": 706,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Learning Python",
        "author": "Mark Lutz",
        "publisher": "O'Reilly Media",
        "published_date": "2025-02-01",
        "page_count": 1169,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Head First Python",
        "author": "Paul Barry",
        "publisher": "O'Reilly Media",
        "published_date": "2023-08-01",
        "page_count": 624,
        "language": "English",
    },
    {
        "id": 9,
        "title": "Python for Everybody",
        "author": "Charles R. Severance",
        "publisher": "CreateSpace",
        "published_date": "2016-01-01",
        "page_count": 247,
        "language": "English",
    },
    {
        "id": 10,
        "title": "Python for Data Analysis",
        "author": "Wes McKinney",
        "publisher": "O'Reilly Media",
        "published_date": "2022-10-01",
        "page_count": 579,
        "language": "English",
    },
    {
        "id": 11,
        "title": "Python Data Science Handbook",
        "author": "Jake VanderPlas",
        "publisher": "O'Reilly Media",
        "published_date": "2016-11-01",
        "page_count": 548,
        "language": "English",
    },
    {
        "id": 12,
        "title": "Grokking Algorithms",
        "author": "Aditya Bhargava",
        "publisher": "Manning Publications",
        "published_date": "2016-05-01",
        "page_count": 256,
        "language": "English",
    },
    {
        "id": 13,
        "title": "Data Structures and Algorithms in Python",
        "author": "Michael T. Goodrich",
        "publisher": "Wiley",
        "published_date": "2013-03-01",
        "page_count": 768,
        "language": "English",
    },
    {
        "id": 14,
        "title": "Problem Solving with Algorithms and Data Structures Using Python",
        "author": "Bradley N. Miller",
        "publisher": "Franklin Beedle & Associates",
        "published_date": "2011-01-01",
        "page_count": 438,
        "language": "English",
    },
    {
        "id": 15,
        "title": "Dive Into Python 3",
        "author": "Mark Pilgrim",
        "publisher": "Apress",
        "published_date": "2009-11-01",
        "page_count": 360,
        "language": "English",
    },
    {
        "id": 16,
        "title": "Python in Practice",
        "author": "Mark Summerfield",
        "publisher": "Addison-Wesley Professional",
        "published_date": "2013-06-01",
        "page_count": 456,
        "language": "English",
    },
    {
        "id": 17,
        "title": "Serious Python",
        "author": "Julien Danjou",
        "publisher": "No Starch Press",
        "published_date": "2018-04-01",
        "page_count": 240,
        "language": "English",
    },
    {
        "id": 18,
        "title": "Architecture Patterns with Python",
        "author": "Harry Percival",
        "publisher": "O'Reilly Media",
        "published_date": "2020-03-01",
        "page_count": 284,
        "language": "English",
    },
    {
        "id": 19,
        "title": "Python Testing with pytest",
        "author": "Brian Okken",
        "publisher": "The Pragmatic Programmers",
        "published_date": "2017-06-01",
        "page_count": 200,
        "language": "English",
    },
    {
        "id": 20,
        "title": "Python High Performance",
        "author": "Gabriele Lanaro",
        "publisher": "Packt Publishing",
        "published_date": "2014-01-01",
        "page_count": 250,
        "language": "English",
    },
]
